Insert Into dx2hub.Demons Values (null, "Abaddon", (Select Race_ID from dx2hub.races where Race_Name = "Tyrant"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 60, 4); 
Insert Into dx2hub.Demons Values (null, "Abaddon A", (Select Race_ID from dx2hub.races where Race_Name = "Tyrant"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 60, 4); 
Insert Into dx2hub.Demons Values (null, "Abraxas", (Select Race_ID from dx2hub.races where Race_Name = "Vile"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 26, 2); 
Insert Into dx2hub.Demons Values (null, "Agathion", (Select Race_ID from dx2hub.races where Race_Name = "Yoma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 5, 1); 
Insert Into dx2hub.Demons Values (null, "Alice", (Select Race_ID from dx2hub.races where Race_Name = "Fiend"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 89, 5); 
Insert Into dx2hub.Demons Values (null, "Alilat", (Select Race_ID from dx2hub.races where Race_Name = "Entity"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 85, 5); 
Insert Into dx2hub.Demons Values (null, "Amaterasu", (Select Race_ID from dx2hub.races where Race_Name = "Deity"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 82, 5); 
Insert Into dx2hub.Demons Values (null, "Ammut", (Select Race_ID from dx2hub.races where Race_Name = "Beast"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 44, 3); 
Insert Into dx2hub.Demons Values (null, "Ananta", (Select Race_ID from dx2hub.races where Race_Name = "Snake"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 83, 5); 
Insert Into dx2hub.Demons Values (null, "Angel", (Select Race_ID from dx2hub.races where Race_Name = "Divine"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 20, 2); 
Insert Into dx2hub.Demons Values (null, "Anubis", (Select Race_ID from dx2hub.races where Race_Name = "Avatar"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 70, 4); 
Insert Into dx2hub.Demons Values (null, "Apis", (Select Race_ID from dx2hub.races where Race_Name = "Holy"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 44, 3); 
Insert Into dx2hub.Demons Values (null, "Apsaras", (Select Race_ID from dx2hub.races where Race_Name = "Yoma"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 11, 1); 
Insert Into dx2hub.Demons Values (null, "Ara Mitama", (Select Race_ID from dx2hub.races where Race_Name = "Mitama"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 21, 2); 
Insert Into dx2hub.Demons Values (null, "Arahabaki", (Select Race_ID from dx2hub.races where Race_Name = "Vile"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 50, 3); 
Insert Into dx2hub.Demons Values (null, "Archangel", (Select Race_ID from dx2hub.races where Race_Name = "Divine"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 25, 2); 
Insert Into dx2hub.Demons Values (null, "Ares", (Select Race_ID from dx2hub.races where Race_Name = "Fury"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 44, 3); 
Insert Into dx2hub.Demons Values (null, "Arianrhod", (Select Race_ID from dx2hub.races where Race_Name = "Megami"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 44, 3); 
Insert Into dx2hub.Demons Values (null, "Asherah", (Select Race_ID from dx2hub.races where Race_Name = "Lady"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 83, 5); 
Insert Into dx2hub.Demons Values (null, "Attis", (Select Race_ID from dx2hub.races where Race_Name = "Zealot"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 65, 4); 
Insert Into dx2hub.Demons Values (null, "Azrael", (Select Race_ID from dx2hub.races where Race_Name = "Herald"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 67, 4); 
Insert Into dx2hub.Demons Values (null, "Azumi", (Select Race_ID from dx2hub.races where Race_Name = "Brute"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 3, 1); 
Insert Into dx2hub.Demons Values (null, "Baihu", (Select Race_ID from dx2hub.races where Race_Name = "Holy"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 48, 3); 
Insert Into dx2hub.Demons Values (null, "Baphomet", (Select Race_ID from dx2hub.races where Race_Name = "Vile"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 41, 3); 
Insert Into dx2hub.Demons Values (null, "Barong", (Select Race_ID from dx2hub.races where Race_Name = "Avatar"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 84, 5); 
Insert Into dx2hub.Demons Values (null, "Bayonetta", (Select Race_ID from dx2hub.races where Race_Name = "Witch"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 65, 4); 
Insert Into dx2hub.Demons Values (null, "Bayonetta☆", (Select Race_ID from dx2hub.races where Race_Name = "Witch"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 85, 5); 
Insert Into dx2hub.Demons Values (null, "Beelzebub", (Select Race_ID from dx2hub.races where Race_Name = "Tyrant"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 68, 4); 
Insert Into dx2hub.Demons Values (null, "Beiji-Weng", (Select Race_ID from dx2hub.races where Race_Name = "Fury"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 69, 4); 
Insert Into dx2hub.Demons Values (null, "Beloved", (Select Race_ID from dx2hub.races where Race_Name = "Divine"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 70, 4); 
Insert Into dx2hub.Demons Values (null, "Berserker", (Select Race_ID from dx2hub.races where Race_Name = "Brute"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 54, 3); 
Insert Into dx2hub.Demons Values (null, "Bicorn", (Select Race_ID from dx2hub.races where Race_Name = "Wilder"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 9, 1); 
Insert Into dx2hub.Demons Values (null, "Bishamonten", (Select Race_ID from dx2hub.races where Race_Name = "Kishin"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 70, 4); 
Insert Into dx2hub.Demons Values (null, "Black Frost", (Select Race_ID from dx2hub.races where Race_Name = "Jaki"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 81, 5); 
Insert Into dx2hub.Demons Values (null, "Black Ooze", (Select Race_ID from dx2hub.races where Race_Name = "Foul"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 25, 2); 
Insert Into dx2hub.Demons Values (null, "Blob", (Select Race_ID from dx2hub.races where Race_Name = "Foul"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 20, 2); 
Insert Into dx2hub.Demons Values (null, "Bodyconian", (Select Race_ID from dx2hub.races where Race_Name = "Undead"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 40, 3); 
Insert Into dx2hub.Demons Values (null, "Cerberus", (Select Race_ID from dx2hub.races where Race_Name = "Beast"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 61, 4); 
Insert Into dx2hub.Demons Values (null, "Chagrin", (Select Race_ID from dx2hub.races where Race_Name = "Wilder"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 4, 1); 
Insert Into dx2hub.Demons Values (null, "Chatterskull", (Select Race_ID from dx2hub.races where Race_Name = "Haunt"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 44, 3); 
Insert Into dx2hub.Demons Values (null, "Chernobog", (Select Race_ID from dx2hub.races where Race_Name = "Reaper"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 64, 4); 
Insert Into dx2hub.Demons Values (null, "Chimera", (Select Race_ID from dx2hub.races where Race_Name = "Avatar"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 49, 3); 
Insert Into dx2hub.Demons Values (null, "Chupacabra", (Select Race_ID from dx2hub.races where Race_Name = "UMA"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 15, 1); 
Insert Into dx2hub.Demons Values (null, "Cu Chulainn", (Select Race_ID from dx2hub.races where Race_Name = "Genma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 81, 5); 
Insert Into dx2hub.Demons Values (null, "Cu Sith", (Select Race_ID from dx2hub.races where Race_Name = "Beast"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 3, 1); 
Insert Into dx2hub.Demons Values (null, "Dakini", (Select Race_ID from dx2hub.races where Race_Name = "Femme"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 53, 3); 
Insert Into dx2hub.Demons Values (null, "Dantalian", (Select Race_ID from dx2hub.races where Race_Name = "Fallen"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 70, 4); 
Insert Into dx2hub.Demons Values (null, "Dante", (Select Race_ID from dx2hub.races where Race_Name = "Fiend"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 70, 4); 
Insert Into dx2hub.Demons Values (null, "Dante☆", (Select Race_ID from dx2hub.races where Race_Name = "Fiend"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 90, 5); 
Insert Into dx2hub.Demons Values (null, "Decarabia", (Select Race_ID from dx2hub.races where Race_Name = "Fallen"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 23, 2); 
Insert Into dx2hub.Demons Values (null, "Dionysus", (Select Race_ID from dx2hub.races where Race_Name = "Zealot"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 64, 4); 
Insert Into dx2hub.Demons Values (null, "Dis", (Select Race_ID from dx2hub.races where Race_Name = "Yoma"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 34, 2); 
Insert Into dx2hub.Demons Values (null, "Dominion", (Select Race_ID from dx2hub.races where Race_Name = "Divine"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 53, 3); 
Insert Into dx2hub.Demons Values (null, "Efreet", (Select Race_ID from dx2hub.races where Race_Name = "Yoma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 52, 3); 
Insert Into dx2hub.Demons Values (null, "Eligor", (Select Race_ID from dx2hub.races where Race_Name = "Fallen"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 10, 1); 
Insert Into dx2hub.Demons Values (null, "Feng Huang", (Select Race_ID from dx2hub.races where Race_Name = "Avian"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 53, 3); 
Insert Into dx2hub.Demons Values (null, "Fenrir", (Select Race_ID from dx2hub.races where Race_Name = "Wilder"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 61, 4); 
Insert Into dx2hub.Demons Values (null, "Fomorian", (Select Race_ID from dx2hub.races where Race_Name = "Night"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 30, 2); 
Insert Into dx2hub.Demons Values (null, "Forneus", (Select Race_ID from dx2hub.races where Race_Name = "Fallen"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 41, 3); 
Insert Into dx2hub.Demons Values (null, "Ganesha", (Select Race_ID from dx2hub.races where Race_Name = "Yoma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 66, 4); 
Insert Into dx2hub.Demons Values (null, "Garuda", (Select Race_ID from dx2hub.races where Race_Name = "Avian"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 80, 5); 
Insert Into dx2hub.Demons Values (null, "Girimekhala", (Select Race_ID from dx2hub.races where Race_Name = "Vile"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 67, 4); 
Insert Into dx2hub.Demons Values (null, "Gremlin", (Select Race_ID from dx2hub.races where Race_Name = "Jaki"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 11, 1); 
Insert Into dx2hub.Demons Values (null, "Grendel", (Select Race_ID from dx2hub.races where Race_Name = "Jaki"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 51, 3); 
Insert Into dx2hub.Demons Values (null, "Gucumatz", (Select Race_ID from dx2hub.races where Race_Name = "Dragon"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 69, 4); 
Insert Into dx2hub.Demons Values (null, "Gui Xian", (Select Race_ID from dx2hub.races where Race_Name = "Snake"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 45, 3); 
Insert Into dx2hub.Demons Values (null, "Halloween Jack", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 65, 4); 
Insert Into dx2hub.Demons Values (null, "Hamsa", (Select Race_ID from dx2hub.races where Race_Name = "Avian"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 24, 2); 
Insert Into dx2hub.Demons Values (null, "Hanuman", (Select Race_ID from dx2hub.races where Race_Name = "Genma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 60, 4); 
Insert Into dx2hub.Demons Values (null, "Hare of Inaba", (Select Race_ID from dx2hub.races where Race_Name = "UMA"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 41, 3); 
Insert Into dx2hub.Demons Values (null, "Hathor", (Select Race_ID from dx2hub.races where Race_Name = "Megami"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 27, 2); 
Insert Into dx2hub.Demons Values (null, "Hecatoncheires", (Select Race_ID from dx2hub.races where Race_Name = "Jaki"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 74, 4); 
Insert Into dx2hub.Demons Values (null, "Hel", (Select Race_ID from dx2hub.races where Race_Name = "Reaper"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 60, 4); 
Insert Into dx2hub.Demons Values (null, "Hell Biker", (Select Race_ID from dx2hub.races where Race_Name = "Fiend"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 77, 4); 
Insert Into dx2hub.Demons Values (null, "Helper Frost", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 63, 4); 
Insert Into dx2hub.Demons Values (null, "Heqet", (Select Race_ID from dx2hub.races where Race_Name = "Holy"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 27, 2); 
Insert Into dx2hub.Demons Values (null, "High Pixie", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 24, 2); 
Insert Into dx2hub.Demons Values (null, "Horkos", (Select Race_ID from dx2hub.races where Race_Name = "Tyrant"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 46, 3); 
Insert Into dx2hub.Demons Values (null, "Horus", (Select Race_ID from dx2hub.races where Race_Name = "Deity"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 49, 3); 
Insert Into dx2hub.Demons Values (null, "Huang Di", (Select Race_ID from dx2hub.races where Race_Name = "Hero"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 88, 5); 
Insert Into dx2hub.Demons Values (null, "Huang Long", (Select Race_ID from dx2hub.races where Race_Name = "Dragon"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 88, 5); 
Insert Into dx2hub.Demons Values (null, "Ikusa", (Select Race_ID from dx2hub.races where Race_Name = "Brute"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 41, 3); 
Insert Into dx2hub.Demons Values (null, "Illuyanka", (Select Race_ID from dx2hub.races where Race_Name = "Dragon"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 47, 3); 
Insert Into dx2hub.Demons Values (null, "Incubus", (Select Race_ID from dx2hub.races where Race_Name = "Night"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 21, 2); 
Insert Into dx2hub.Demons Values (null, "Inugami", (Select Race_ID from dx2hub.races where Race_Name = "Beast"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 9, 1); 
Insert Into dx2hub.Demons Values (null, "Ippon-Datara", (Select Race_ID from dx2hub.races where Race_Name = "Jaki"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 26, 2); 
Insert Into dx2hub.Demons Values (null, "Ishtar", (Select Race_ID from dx2hub.races where Race_Name = "Megami"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 82, 5); 
Insert Into dx2hub.Demons Values (null, "Isis", (Select Race_ID from dx2hub.races where Race_Name = "Lady"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 54, 3); 
Insert Into dx2hub.Demons Values (null, "Ixtab", (Select Race_ID from dx2hub.races where Race_Name = "Reaper"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 84, 5); 
Insert Into dx2hub.Demons Values (null, "Izanami", (Select Race_ID from dx2hub.races where Race_Name = "Megami"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 89, 5); 
Insert Into dx2hub.Demons Values (null, "Jack Frost", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 7, 1); 
Insert Into dx2hub.Demons Values (null, "Jatayu", (Select Race_ID from dx2hub.races where Race_Name = "Avian"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 44, 3); 
Insert Into dx2hub.Demons Values (null, "Jeanne", (Select Race_ID from dx2hub.races where Race_Name = "Witch"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 65, 4); 
Insert Into dx2hub.Demons Values (null, "Jeanne d'Arc", (Select Race_ID from dx2hub.races where Race_Name = "Hero"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 78, 4); 
Insert Into dx2hub.Demons Values (null, "Jeanne☆", (Select Race_ID from dx2hub.races where Race_Name = "Witch"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 85, 5); 
Insert Into dx2hub.Demons Values (null, "Jikokuten", (Select Race_ID from dx2hub.races where Race_Name = "Kishin"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 62, 4); 
Insert Into dx2hub.Demons Values (null, "Kaiwan", (Select Race_ID from dx2hub.races where Race_Name = "Night"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 42, 3); 
Insert Into dx2hub.Demons Values (null, "Kama", (Select Race_ID from dx2hub.races where Race_Name = "Enigma"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 75, 4); 
Insert Into dx2hub.Demons Values (null, "Kamiotoko", (Select Race_ID from dx2hub.races where Race_Name = "Rumor"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 25, 2); 
Insert Into dx2hub.Demons Values (null, "Kanbari", (Select Race_ID from dx2hub.races where Race_Name = "Enigma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 30, 2); 
Insert Into dx2hub.Demons Values (null, "Kelpie", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 35, 2); 
Insert Into dx2hub.Demons Values (null, "Kikuri-Hime", (Select Race_ID from dx2hub.races where Race_Name = "Lady"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 60, 4); 
Insert Into dx2hub.Demons Values (null, "King Frost", (Select Race_ID from dx2hub.races where Race_Name = "Tyrant"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 64, 4); 
Insert Into dx2hub.Demons Values (null, "Kinmamon", (Select Race_ID from dx2hub.races where Race_Name = "Enigma"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 55, 3); 
Insert Into dx2hub.Demons Values (null, "Koppa Tengu", (Select Race_ID from dx2hub.races where Race_Name = "Yoma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 7, 1); 
Insert Into dx2hub.Demons Values (null, "Koumokuten", (Select Race_ID from dx2hub.races where Race_Name = "Kishin"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 50, 3); 
Insert Into dx2hub.Demons Values (null, "Kresnik", (Select Race_ID from dx2hub.races where Race_Name = "Genma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 49, 3); 
Insert Into dx2hub.Demons Values (null, "Kudlak", (Select Race_ID from dx2hub.races where Race_Name = "Jaki"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 67, 4); 
Insert Into dx2hub.Demons Values (null, "Kurama Tengu", (Select Race_ID from dx2hub.races where Race_Name = "Genma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 27, 2); 
Insert Into dx2hub.Demons Values (null, "Kushinada", (Select Race_ID from dx2hub.races where Race_Name = "Lady"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 47, 3); 
Insert Into dx2hub.Demons Values (null, "Kusi Mitama", (Select Race_ID from dx2hub.races where Race_Name = "Mitama"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 31, 2); 
Insert Into dx2hub.Demons Values (null, "Lailah", (Select Race_ID from dx2hub.races where Race_Name = "Herald"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 43, 3); 
Insert Into dx2hub.Demons Values (null, "Lakshmi", (Select Race_ID from dx2hub.races where Race_Name = "Megami"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 85, 5); 
Insert Into dx2hub.Demons Values (null, "Leanan Sidhe", (Select Race_ID from dx2hub.races where Race_Name = "Femme"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 12, 1); 
Insert Into dx2hub.Demons Values (null, "Legion", (Select Race_ID from dx2hub.races where Race_Name = "Haunt"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 34, 2); 
Insert Into dx2hub.Demons Values (null, "Lilim", (Select Race_ID from dx2hub.races where Race_Name = "Night"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 47, 3); 
Insert Into dx2hub.Demons Values (null, "Lilith", (Select Race_ID from dx2hub.races where Race_Name = "Night"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 80, 5); 
Insert Into dx2hub.Demons Values (null, "Loki", (Select Race_ID from dx2hub.races where Race_Name = "Tyrant"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 75, 4); 
Insert Into dx2hub.Demons Values (null, "Long", (Select Race_ID from dx2hub.races where Race_Name = "Dragon"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 63, 4); 
Insert Into dx2hub.Demons Values (null, "Lucifer", (Select Race_ID from dx2hub.races where Race_Name = "Tyrant"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 98, 5); 
Insert Into dx2hub.Demons Values (null, "Mad Gasser", (Select Race_ID from dx2hub.races where Race_Name = "Foul"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 45, 3); 
Insert Into dx2hub.Demons Values (null, "Makami", (Select Race_ID from dx2hub.races where Race_Name = "Avatar"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 41, 3); 
Insert Into dx2hub.Demons Values (null, "Makara", (Select Race_ID from dx2hub.races where Race_Name = "Dragon"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 41, 3); 
Insert Into dx2hub.Demons Values (null, "Man Eater", (Select Race_ID from dx2hub.races where Race_Name = "Undead"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 60, 4); 
Insert Into dx2hub.Demons Values (null, "Mara", (Select Race_ID from dx2hub.races where Race_Name = "Tyrant"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 90, 5); 
Insert Into dx2hub.Demons Values (null, "Masakado", (Select Race_ID from dx2hub.races where Race_Name = "General"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 98, 5); 
Insert Into dx2hub.Demons Values (null, "Mastema", (Select Race_ID from dx2hub.races where Race_Name = "Herald"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 83, 5); 
Insert Into dx2hub.Demons Values (null, "Matador", (Select Race_ID from dx2hub.races where Race_Name = "Fiend"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 73, 4); 
Insert Into dx2hub.Demons Values (null, "Melchom", (Select Race_ID from dx2hub.races where Race_Name = "Fallen"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 4, 1); 
Insert Into dx2hub.Demons Values (null, "Mermaid", (Select Race_ID from dx2hub.races where Race_Name = "Femme"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 42, 3); 
Insert Into dx2hub.Demons Values (null, "Metatron", (Select Race_ID from dx2hub.races where Race_Name = "Herald"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 99, 5); 
Insert Into dx2hub.Demons Values (null, "Michael", (Select Race_ID from dx2hub.races where Race_Name = "Herald"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 90, 5); 
Insert Into dx2hub.Demons Values (null, "Mishaguji", (Select Race_ID from dx2hub.races where Race_Name = "Vile"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 65, 4); 
Insert Into dx2hub.Demons Values (null, "Mitra", (Select Race_ID from dx2hub.races where Race_Name = "Deity"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 55, 3); 
Insert Into dx2hub.Demons Values (null, "Mokoi", (Select Race_ID from dx2hub.races where Race_Name = "Night"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 5, 1); 
Insert Into dx2hub.Demons Values (null, "Momunofu", (Select Race_ID from dx2hub.races where Race_Name = "Brute"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 15, 1); 
Insert Into dx2hub.Demons Values (null, "Mot", (Select Race_ID from dx2hub.races where Race_Name = "Reaper"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 91, 5); 
Insert Into dx2hub.Demons Values (null, "Mother Harlot", (Select Race_ID from dx2hub.races where Race_Name = "Fiend"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 95, 5); 
Insert Into dx2hub.Demons Values (null, "Mothman", (Select Race_ID from dx2hub.races where Race_Name = "Wilder"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 41, 3); 
Insert Into dx2hub.Demons Values (null, "Mou-Ryo", (Select Race_ID from dx2hub.races where Race_Name = "Haunt"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 20, 2); 
Insert Into dx2hub.Demons Values (null, "Naga", (Select Race_ID from dx2hub.races where Race_Name = "Snake"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 28, 2); 
Insert Into dx2hub.Demons Values (null, "Nekomata", (Select Race_ID from dx2hub.races where Race_Name = "Beast"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 14, 1); 
Insert Into dx2hub.Demons Values (null, "Nekomata A", (Select Race_ID from dx2hub.races where Race_Name = "Beast"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 60, 4); 
Insert Into dx2hub.Demons Values (null, "Nergal", (Select Race_ID from dx2hub.races where Race_Name = "Reaper"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 81, 5); 
Insert Into dx2hub.Demons Values (null, "Nero", (Select Race_ID from dx2hub.races where Race_Name = "Fiend"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 70, 4); 
Insert Into dx2hub.Demons Values (null, "Nero☆", (Select Race_ID from dx2hub.races where Race_Name = "Fiend"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 90, 5); 
Insert Into dx2hub.Demons Values (null, "Nigi Mitama", (Select Race_ID from dx2hub.races where Race_Name = "Mitama"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 26, 2); 
Insert Into dx2hub.Demons Values (null, "Nozuchi", (Select Race_ID from dx2hub.races where Race_Name = "Snake"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 15, 1); 
Insert Into dx2hub.Demons Values (null, "Nue", (Select Race_ID from dx2hub.races where Race_Name = "Wilder"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 25, 2); 
Insert Into dx2hub.Demons Values (null, "Obariyon", (Select Race_ID from dx2hub.races where Race_Name = "Haunt"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 7, 1); 
Insert Into dx2hub.Demons Values (null, "Oberon", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 67, 4); 
Insert Into dx2hub.Demons Values (null, "Odin", (Select Race_ID from dx2hub.races where Race_Name = "Deity"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 73, 4); 
Insert Into dx2hub.Demons Values (null, "Ongyo-Ki", (Select Race_ID from dx2hub.races where Race_Name = "Brute"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 68, 4); 
Insert Into dx2hub.Demons Values (null, "Oni", (Select Race_ID from dx2hub.races where Race_Name = "Brute"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 27, 2); 
Insert Into dx2hub.Demons Values (null, "Orcus", (Select Race_ID from dx2hub.races where Race_Name = "Reaper"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 80, 5); 
Insert Into dx2hub.Demons Values (null, "Orochi", (Select Race_ID from dx2hub.races where Race_Name = "Snake"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 61, 4); 
Insert Into dx2hub.Demons Values (null, "Orthrus", (Select Race_ID from dx2hub.races where Race_Name = "Beast"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 35, 2); 
Insert Into dx2hub.Demons Values (null, "Ose", (Select Race_ID from dx2hub.races where Race_Name = "Fallen"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 54, 3); 
Insert Into dx2hub.Demons Values (null, "Pallas Athena", (Select Race_ID from dx2hub.races where Race_Name = "Megami"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 62, 4); 
Insert Into dx2hub.Demons Values (null, "Patrimpas", (Select Race_ID from dx2hub.races where Race_Name = "Dragon"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 35, 2); 
Insert Into dx2hub.Demons Values (null, "Pazuzu", (Select Race_ID from dx2hub.races where Race_Name = "Vile"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 62, 4); 
Insert Into dx2hub.Demons Values (null, "Peallaidh", (Select Race_ID from dx2hub.races where Race_Name = "Wilder"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 46, 3); 
Insert Into dx2hub.Demons Values (null, "Pele", (Select Race_ID from dx2hub.races where Race_Name = "Lady"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 40, 3); 
Insert Into dx2hub.Demons Values (null, "Persephone", (Select Race_ID from dx2hub.races where Race_Name = "Reaper"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 72, 4); 
Insert Into dx2hub.Demons Values (null, "Phantom", (Select Race_ID from dx2hub.races where Race_Name = "Foul"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 10, 1); 
Insert Into dx2hub.Demons Values (null, "Pisaca", (Select Race_ID from dx2hub.races where Race_Name = "Haunt"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 26, 2); 
Insert Into dx2hub.Demons Values (null, "Pixie", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 2, 1); 
Insert Into dx2hub.Demons Values (null, "Power", (Select Race_ID from dx2hub.races where Race_Name = "Divine"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 40, 3); 
Insert Into dx2hub.Demons Values (null, "Preta", (Select Race_ID from dx2hub.races where Race_Name = "Haunt"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 4, 1); 
Insert Into dx2hub.Demons Values (null, "Principality", (Select Race_ID from dx2hub.races where Race_Name = "Divine"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 35, 2); 
Insert Into dx2hub.Demons Values (null, "Prometheus", (Select Race_ID from dx2hub.races where Race_Name = "Deity"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 67, 4); 
Insert Into dx2hub.Demons Values (null, "Pyro Jack", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 13, 1); 
Insert Into dx2hub.Demons Values (null, "Quetzalcoatl", (Select Race_ID from dx2hub.races where Race_Name = "Dragon"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 80, 5); 
Insert Into dx2hub.Demons Values (null, "Raijuu", (Select Race_ID from dx2hub.races where Race_Name = "Wilder"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 20, 2); 
Insert Into dx2hub.Demons Values (null, "Rakshasa", (Select Race_ID from dx2hub.races where Race_Name = "Jaki"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 61, 4); 
Insert Into dx2hub.Demons Values (null, "Rama", (Select Race_ID from dx2hub.races where Race_Name = "Hero"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 86, 5); 
Insert Into dx2hub.Demons Values (null, "Rangda", (Select Race_ID from dx2hub.races where Race_Name = "Femme"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 67, 4); 
Insert Into dx2hub.Demons Values (null, "Reiko Kashima", (Select Race_ID from dx2hub.races where Race_Name = "Rumor"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 42, 3); 
Insert Into dx2hub.Demons Values (null, "Saki Mitama", (Select Race_ID from dx2hub.races where Race_Name = "Mitama"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 36, 2); 
Insert Into dx2hub.Demons Values (null, "Samael", (Select Race_ID from dx2hub.races where Race_Name = "Fallen"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 84, 5); 
Insert Into dx2hub.Demons Values (null, "Sandalphon", (Select Race_ID from dx2hub.races where Race_Name = "Herald"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 61, 4); 
Insert Into dx2hub.Demons Values (null, "Sandman", (Select Race_ID from dx2hub.races where Race_Name = "Night"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 10, 1); 
Insert Into dx2hub.Demons Values (null, "Sarasvati", (Select Race_ID from dx2hub.races where Race_Name = "Megami"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 69, 4); 
Insert Into dx2hub.Demons Values (null, "Scathach", (Select Race_ID from dx2hub.races where Race_Name = "Megami"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 50, 3); 
Insert Into dx2hub.Demons Values (null, "Setanta", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 47, 3); 
Insert Into dx2hub.Demons Values (null, "Seth", (Select Race_ID from dx2hub.races where Race_Name = "Vile"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 84, 5); 
Insert Into dx2hub.Demons Values (null, "Shadow", (Select Race_ID from dx2hub.races where Race_Name = "Foul"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 35, 2); 
Insert Into dx2hub.Demons Values (null, "Shiisaa", (Select Race_ID from dx2hub.races where Race_Name = "Avatar"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 33, 2); 
Insert Into dx2hub.Demons Values (null, "Shiki-Ouji", (Select Race_ID from dx2hub.races where Race_Name = "Brute"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 49, 3); 
Insert Into dx2hub.Demons Values (null, "Shikome", (Select Race_ID from dx2hub.races where Race_Name = "Femme"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 23, 2); 
Insert Into dx2hub.Demons Values (null, "Shiva", (Select Race_ID from dx2hub.races where Race_Name = "Fury"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 93, 5); 
Insert Into dx2hub.Demons Values (null, "Shiva A", (Select Race_ID from dx2hub.races where Race_Name = "Fury"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 93, 5); 
Insert Into dx2hub.Demons Values (null, "Siegfried", (Select Race_ID from dx2hub.races where Race_Name = "Hero"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 83, 5); 
Insert Into dx2hub.Demons Values (null, "Silky", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 42, 3); 
Insert Into dx2hub.Demons Values (null, "Skadi", (Select Race_ID from dx2hub.races where Race_Name = "Lady"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 67, 4); 
Insert Into dx2hub.Demons Values (null, "Sleipnir", (Select Race_ID from dx2hub.races where Race_Name = "Holy"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 62, 4); 
Insert Into dx2hub.Demons Values (null, "Slime", (Select Race_ID from dx2hub.races where Race_Name = "Foul"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 1, 1); 
Insert Into dx2hub.Demons Values (null, "Sphinx", (Select Race_ID from dx2hub.races where Race_Name = "Holy"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 76, 4); 
Insert Into dx2hub.Demons Values (null, "Succubus", (Select Race_ID from dx2hub.races where Race_Name = "Night"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 63, 4); 
Insert Into dx2hub.Demons Values (null, "Suparna", (Select Race_ID from dx2hub.races where Race_Name = "Avian"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 28, 2); 
Insert Into dx2hub.Demons Values (null, "Surt", (Select Race_ID from dx2hub.races where Race_Name = "Tyrant"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 83, 5); 
Insert Into dx2hub.Demons Values (null, "Susano-o", (Select Race_ID from dx2hub.races where Race_Name = "Fury"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 82, 5); 
Insert Into dx2hub.Demons Values (null, "Take-Minakata", (Select Race_ID from dx2hub.races where Race_Name = "Kishin"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 27, 2); 
Insert Into dx2hub.Demons Values (null, "Tam Lin", (Select Race_ID from dx2hub.races where Race_Name = "Genma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 40, 3); 
Insert Into dx2hub.Demons Values (null, "Thor", (Select Race_ID from dx2hub.races where Race_Name = "Kishin"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 83, 5); 
Insert Into dx2hub.Demons Values (null, "Throne", (Select Race_ID from dx2hub.races where Race_Name = "Divine"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 60, 4); 
Insert Into dx2hub.Demons Values (null, "Titania", (Select Race_ID from dx2hub.races where Race_Name = "Fairy"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 62, 4); 
Insert Into dx2hub.Demons Values (null, "Trumpeter", (Select Race_ID from dx2hub.races where Race_Name = "Fiend"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 94, 5); 
Insert Into dx2hub.Demons Values (null, "Tsukuyomi", (Select Race_ID from dx2hub.races where Race_Name = "Genma"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 67, 4); 
Insert Into dx2hub.Demons Values (null, "Unicorn", (Select Race_ID from dx2hub.races where Race_Name = "Holy"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 42, 3); 
Insert Into dx2hub.Demons Values (null, "V", (Select Race_ID from dx2hub.races where Race_Name = "??"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 70, 4); 
Insert Into dx2hub.Demons Values (null, "V☆", (Select Race_ID from dx2hub.races where Race_Name = "??"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 90, 5); 
Insert Into dx2hub.Demons Values (null, "Valkyrie", (Select Race_ID from dx2hub.races where Race_Name = "Yoma"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 40, 3); 
Insert Into dx2hub.Demons Values (null, "Vetala", (Select Race_ID from dx2hub.races where Race_Name = "Haunt"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 55, 3); 
Insert Into dx2hub.Demons Values (null, "Virtue", (Select Race_ID from dx2hub.races where Race_Name = "Divine"), (Select AI_ID from dx2hub.races where AI_Name = "Heal"), 47, 3); 
Insert Into dx2hub.Demons Values (null, "Vishnu", (Select Race_ID from dx2hub.races where Race_Name = "Deity"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 97, 5); 
Insert Into dx2hub.Demons Values (null, "White Rider", (Select Race_ID from dx2hub.races where Race_Name = "Fiend"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 74, 4); 
Insert Into dx2hub.Demons Values (null, "Wu Kong", (Select Race_ID from dx2hub.races where Race_Name = "Fury"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 61, 4); 
Insert Into dx2hub.Demons Values (null, "Yaksini", (Select Race_ID from dx2hub.races where Race_Name = "Femme"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 34, 2); 
Insert Into dx2hub.Demons Values (null, "Yatagarasu", (Select Race_ID from dx2hub.races where Race_Name = "Avian"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 66, 4); 
Insert Into dx2hub.Demons Values (null, "Yoshitsune", (Select Race_ID from dx2hub.races where Race_Name = "Hero"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 97, 5); 
Insert Into dx2hub.Demons Values (null, "Yurlungur", (Select Race_ID from dx2hub.races where Race_Name = "Snake"), (Select AI_ID from dx2hub.races where AI_Name = "Support"), 70, 4); 
Insert Into dx2hub.Demons Values (null, "Zaou-Gongen", (Select Race_ID from dx2hub.races where Race_Name = "Fury"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 85, 5); 
Insert Into dx2hub.Demons Values (null, "Zhong Kui", (Select Race_ID from dx2hub.races where Race_Name = "Kishin"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 75, 4); 
Insert Into dx2hub.Demons Values (null, "Zouchouten", (Select Race_ID from dx2hub.races where Race_Name = "Kishin"), (Select AI_ID from dx2hub.races where AI_Name = "Attack"), 41, 3); 
Insert Into dx2hub.Demons Values (null, "", (Select Race_ID from dx2hub.races where Race_Name = ""), (Select AI_ID from dx2hub.races where AI_Name = ""), , ); 
